services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: urldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data   # data persists between restarts

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:devpass@db:5432/urldb
      REDIS_URL: redis://redis:6379
      BASE_URL: http://localhost:8000
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
